### ISSUE TITLE
Standardbrain registration error

### ISSUE THREAD

**Issue by loli** [lweckeck/LesionPypeline#1]
Hey Lennart,

I get an error when running **albo**.

`albo run -i 00hepoks_29 MR_Flair:00hepoks/29/flair_tra.nii.gz MR_T1:00hepoks/29/t1_sag_tfe.nii.gz`

leads to

> INFO: Resampling...
> INFO: Skullstripping...
> INFO: Biasfield correction...
> INFO: Intensityrange standardization...
> INFO: Extracting features...
> INFO: Applying classifier...
> INFO: Standardbrain registration...
> Traceback (most recent call last):
>   File "/home/maier/.local/bin/albo", line 9, in <module>
>     load_entry_point('Albo', 'console_scripts', 'albo')()
>   File "/home/maier/Workspacepython/albo/albo/**init**.py", line 26, in main
>     args.func(args)
>   File "/home/maier/Workspacepython/albo/albo/albo_run.py", line 51, in main
>     stdbrain_sequence, stdbrain_path)
>   File "/home/maier/Workspacepython/albo/albo/pipeline.py", line 57, in segment_case
>     auxilliary_transform=transforms[standardbrain_sequence])
>   File "/home/maier/Workspacepython/albo/albo/pipeline.py", line 257, in register_to_standardbrain
>     interp="nearestneighbour"
>   File "/home/maier/.local/lib/python2.7/site-packages/nipype/caching/memory.py", line 69, in **call**
>     interface.inputs.set(**kwargs)
>   File "/home/maier/.local/lib/python2.7/site-packages/traits/has_traits.py", line 1541, in trait_set
>     setattr( self, name, value )
>   File "/home/maier/.local/lib/python2.7/site-packages/nipype/interfaces/traits_extension.py", line 80, in validate
>     self.error( object, name, value )
>   File "/home/maier/.local/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
>     value )
> 
> traits.trait_errors.TraitError: The 'reference' trait of an ApplyXfmInputSpec instance must be an existing file name, but a value of '00hepoks/29/t1_sag_tfe.nii.gz' <type 'str'> was specified.`

But `ls 00hepoks/29/t1_sag_tfe.nii.gz` tells me that the file exists.  Any idea what might cause this? Maybe the underscores in the filename?

With other files following the same naming schema I get the same error, but with the following not

`albo run -i 00sisstest_36 MR_Flair:00sisstest/36/FLAIR.nii MR_T1:00sisstest/36/T1.nii`

`albo run -i 00hepoks_27  MR_Flair:00hepoks/27/flair_tra.nii.gz`

`albo run -i 00hepoks_27 MR_Flair:00hepoks/27/flair_tra.nii.gz MR_T2:00hepoks/27/t2_sag_tse.nii.gz`

Is the T1 somehow treated differently than the T2 or FLAIR to MNI registration?

**Comment by lweckeck** [comment]
Hm, I cannot reproduce this issue. However, I will probably reimplement the standardbrain mechanism anyways, see my recent e-mail.
