### ISSUE TITLE
File doesn't exists error

### ISSUE THREAD

**Issue by loli** [lweckeck/LesionPypeline#4]
When running

`albo run -i 00hepoks_10 --cache 01hepoksc --output 02hepokso  MR_Flair:00hepoks/10/flair_tra.nii.gz -f` 

 I get the following error

> INFO: Applying classifier...
> Traceback (most recent call last):
>   File "/home/maier/.local/bin/albo", line 9, in <module>
>     load_entry_point('Albo', 'console_scripts', 'albo')()
>   File "/home/maier/Workspacepython/albo/albo/**init**.py", line 26, in main
>     args.func(args)
>   File "/home/maier/Workspacepython/albo/albo/albo_run.py", line 51, in main
>     stdbrain_sequence, stdbrain_path)
>   File "/home/maier/Workspacepython/albo/albo/pipeline.py", line 46, in segment_case
>     _, header = mio.load(sequences[standardbrain_sequence])
>   File "/home/maier/Workspacepython/medpy/medpy/io/load.py", line 168, in load
>     raise ImageLoadingError('The supplied image {} does not exist.'.format(image))
> medpy.core.exceptions.ImageLoadingError: The supplied image 00hepoks/10/flair_tra.nii.gz does not exist.
> done.

The file `00hepoks/10/flair_tra.nii.gz` exists. Repeating the procedures leads to the same results. 

Looking at the code, I notice that at this point the working directory (`import os; print os.getcdw()`) is set to a temporary cache dir
`/data_humbug1/maier/Temp_Playground/alboregistration/01hepoksc/albo-interfaces-medpy-MedpyIntensityRangeStandardization/644f027c793974b4c797ae77ff04e9fe`
but only for most cases! Sometimes, e.g. for case 01, it is still in
`/data_humbug1/maier/Temp_Playground/alboregistration`
and the script works quite fine.

Any idea why this happens?

PS: The cases where it fails seems to be the ones where the IntensityRangeStandardization could not be executed without a loss of information, i.e., your fallback script seems to change the current working directory somehow, which it shouldn't.

**Comment by loli** [comment]
Fixed with commit https://github.com/lweckeck/albo/commit/ed0c411a7773076c401907633f76deb818d18da0
